theme: jekyll-theme-cayman
title: flaat
description: Flaat has been created to promote the safety of Canadians and to flatten the curve of COVID-19. Giving Canadians the choice to share location and bluetooth capabilities of their mobile devices, helps stop the spread by identifying areas of COVID-19 concentration and notifying individuals who have potentially been exposed to COVID-19.
